# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**


Columna	Tipo	Descripción  
Name	str	Nombre del Pokémon  
Type 1	str	Tipo principal  
Type 2	str/NaN	Tipo secundario  
HP	int/float	Vida base (3 NaN)  
Attack	int	Ataque físico  
Defense	int	Defensa física  
Sp. Atk	int	Ataque especial  
Sp. Def	int	Defensa especial  
Speed	int	Velocidad  
Generation	int	Generación (1–6)  
Legendary	bool	¿Es legendario?

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [ ]:
import pandas as pd
from scipy.stats import ttest_ind  #para los test

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df.head()

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

LE ECHO UN VISTAZO A LO QUE TIENE ESTE DATAFRAME

In [3]:
df.apply(lambda col: col.apply(lambda x: type(x).__name__).value_counts())

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
bool,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800.0
float,1.0,NaN,386.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
int,NaN,NaN,NaN,800.0,800.0,800.0,800.0,800.0,800.0,800.0,NaN
str,799.0,800.0,414.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Voy a verlo tb de otra manera para confirmar lo que tengo

In [4]:


df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")

# --- INFORME COMPLETO ---
print("=== INFORME COMPLETO DEL DATAFRAME ===")

for col in df.columns:

    print(f"\n🔹 Cantidad de valores únicos para {col}:")
    print(df[col].nunique(dropna=False))

    print(f"\n🔹 Tipos internos y cantidades para {col}:")
    print(f"{df[col].apply(lambda x: type(x).__name__).value_counts(dropna=False)}")

    print(f"\n🔹 Cantidad de NaN para {col}:")
    print(df[col].isna().sum())
    print("------------------------------------------------------")

=== INFORME COMPLETO DEL DATAFRAME ===

🔹 Cantidad de valores únicos para Name:
800

🔹 Tipos internos y cantidades para Name:
Name
str      799
float      1
Name: count, dtype: int64

🔹 Cantidad de NaN para Name:
1
------------------------------------------------------

🔹 Cantidad de valores únicos para Type 1:
18

🔹 Tipos internos y cantidades para Type 1:
Type 1
str    800
Name: count, dtype: int64

🔹 Cantidad de NaN para Type 1:
0
------------------------------------------------------

🔹 Cantidad de valores únicos para Type 2:
19

🔹 Tipos internos y cantidades para Type 2:
Type 2
str      414
float    386
Name: count, dtype: int64

🔹 Cantidad de NaN para Type 2:
386
------------------------------------------------------

🔹 Cantidad de valores únicos para HP:
94

🔹 Tipos internos y cantidades para HP:
HP
int    800
Name: count, dtype: int64

🔹 Cantidad de NaN para HP:
0
------------------------------------------------------

🔹 Cantidad de valores únicos para Attack:
111

🔹 Tipos internos y cantidades para Attack:
Attack
int    800
Name: count, dtype: int64

🔹 Cantidad de NaN para Attack:
0
------------------------------------------------------

🔹 Cantidad de valores únicos para Defense:
103

🔹 Tipos internos y cantidades para Defense:
Defense
int    800
Name: count, dtype: int64

🔹 Cantidad de NaN para Defense:
0
------------------------------------------------------

🔹 Cantidad de valores únicos para Sp. Atk:
105

🔹 Tipos internos y cantidades para Sp. Atk:
Sp. Atk
int    800
Name: count, dtype: int64

🔹 Cantidad de NaN para Sp. Atk:
0
------------------------------------------------------

🔹 Cantidad de valores únicos para Sp. Def:
92

🔹 Tipos internos y cantidades para Sp. Def:
Sp. Def
int    800
Name: count, dtype: int64

🔹 Cantidad de NaN para Sp. Def:
0
------------------------------------------------------

🔹 Cantidad de valores únicos para Speed:
108

🔹 Tipos internos y cantidades para Speed:
Speed
int    800
Name: count, dtype: int64

🔹 Cantidad de NaN para Speed:
0
------------------------------------------------------

🔹 Cantidad de valores únicos para Generation:
6

🔹 Tipos internos y cantidades para Generation:
Generation
int    800
Name: count, dtype: int64

🔹 Cantidad de NaN para Generation:
0
------------------------------------------------------

🔹 Cantidad de valores únicos para Legendary:
2

🔹 Tipos internos y cantidades para Legendary:
Legendary
bool    800
Name: count, dtype: int64

🔹 Cantidad de NaN para Legendary:
0
------------------------------------------------------

---

Vemos que hay una celda diferente en Name. La voy a quitar por que no afecta a 800 columnas

En Name vamos a ver cual es el float

In [5]:
filas_float = df[df['Name'].apply(lambda x: isinstance(x, float))]
filas_float

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
62,NaN,Fighting,NaN,65,105,60,60,70,95,1,False

Elimino esa fila , una carta de 800 tampoco influye nada.
Como se el indice la borro facil

In [6]:
df = df.drop(index= 62).reset_index(drop=True) # para seguir limpiando reseteo el indice
df.shape

(799, 11)

In [7]:
# Vamos a ver que hay en las columnas type1 y type2
print(df['Type 1'].unique())
print("------------------------")
print(df['Type 2'].unique())

<StringArray>
[   'Grass',     'Fire',    'Water',      'Bug',   'Normal',   'Poison',
 'Electric',   'Ground',    'Fairy', 'Fighting',  'Psychic',     'Rock',
    'Ghost',      'Ice',   'Dragon',     'Dark',    'Steel',   'Flying']
Length: 18, dtype: str
------------------------
<StringArray>
[  'Poison',        nan,   'Flying',   'Dragon',   'Ground',    'Fairy',
    'Grass', 'Fighting',  'Psychic',    'Steel',      'Ice',     'Rock',
     'Dark',    'Water', 'Electric',     'Fire',    'Ghost',      'Bug',
   'Normal']
Length: 19, dtype: str

In [8]:
# Vamos a ver los tipos de esas columnas 
lista_tipos = ['Type 1', 'Type 2']
for col in lista_tipos:
    print(df[col].value_counts(dropna=False))
    print("------------------------------------")

Type 1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Ground       32
Ghost        32
Dragon       32
Dark         31
Poison       28
Steel        27
Fighting     26
Ice          24
Fairy        17
Flying        4
Name: count, dtype: int64
------------------------------------
Type 2
NaN         385
Flying       97
Ground       35
Poison       34
Psychic      33
Fighting     26
Grass        25
Fairy        23
Steel        22
Dark         20
Dragon       18
Ice          14
Rock         14
Water        14
Ghost        14
Fire         12
Electric      6
Normal        4
Bug           3
Name: count, dtype: int64
------------------------------------

---

* Challenge 1

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass.  
 Choose the propper test and, with 5% significance, comment your findings.

In [9]:
# H0:  HP Dragons = HP Grass  (hipotesis nula)
# H1:  HP Dragons > HP Grass  (lo que queremos demostrar)

from scipy.stats import ttest_ind

dragon_hp = df[df['Type 1'] == 'Dragon']['HP'].dropna()  # miramos los Type_1 sus HP
grass_hp  = df[df['Type 1'] == 'Grass']['HP'].dropna()

t_stat, p_value = ttest_ind(dragon_hp, grass_hp, equal_var=False)

alpha = 0.05

print("p_value =", p_value)

if p_value < alpha:
    print("Rechazamos hipotesis nula  H0: Pokémon tipo Dragon tiene mas HP que Pokémon tipo Grass.")
else:
    print("No rechazamos la hipotesis nula , pero tampoco podemos asegurar que  Pokémon tipo Dragon tiene mas HP que Pokémon tipo Grass.")

p_value = 0.0015987219490841203
Rechazamos hipotesis nula  H0: Pokémon tipo Dragon tiene mas HP que Pokémon tipo Grass.

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary.  
 Choose the propper test and, with 5% significance, comment your findings.

In [10]:
df.head()

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [11]:
# H0:  Legendary(Attack, Defense, Sp. Atk, Sp. Def, Speed)  = No_Legendary(Attack, Defense, Sp. Atk, Sp. Def, Speed)  (hipotesis nula)
# H1:  Legendary(Attack, Defense, Sp. Atk, Sp. Def, Speed)  != No_Legendary(Attack, Defense, Sp. Atk, Sp. Def, Speed)  (queremos demostrar)

from scipy.stats import ttest_ind

stats = ['HP','Attack','Defense','Sp. Atk','Sp. Def','Speed']
alpha = 0.05 

for col in stats:
    legendary = df[df['Legendary'] == True][col].dropna()   # Cada grupo limpia sus propios NaN, porque no depende del otro.
    non_legendary = df[df['Legendary'] == False][col].dropna()
    
    t_stat, p_value = ttest_ind(legendary, non_legendary, equal_var=False)


    print("p_value =", p_value )

    if round(p_value,2) < alpha:
        print(f"Rechazamos hipotesis nula {col} Legendary = {col} No_Legendary")
    else:
        print(f"No rechazamos la hipotesis nula , pero tampoco podemos asegurar que {col} Legendary = {col} No_Legendary")
    print("------------------------------------------")

p_value = 1.0086617990318104e-13
Rechazamos hipotesis nula HP Legendary = HP No_Legendary
------------------------------------------
p_value = 2.411790840368659e-16
Rechazamos hipotesis nula Attack Legendary = Attack No_Legendary
------------------------------------------
p_value = 4.9269277035019174e-11
Rechazamos hipotesis nula Defense Legendary = Defense No_Legendary
------------------------------------------
p_value = 1.5653966266115418e-21
Rechazamos hipotesis nula Sp. Atk Legendary = Sp. Atk No_Legendary
------------------------------------------
p_value = 2.290991957008136e-15
Rechazamos hipotesis nula Sp. Def Legendary = Sp. Def No_Legendary
------------------------------------------
p_value = 9.88726762495576e-19
Rechazamos hipotesis nula Speed Legendary = Speed No_Legendary
------------------------------------------

Resultado :  
Utilizando una Two Sample T-test con un nivel de significancia del 5%, comparamos las estadísticas de Pokémon legendarios y no legendarios en HP, Ataque, Defensa, Sp. Atk, sp. Defensa y velocidad.
En los seis casos se rechaza la hipotesis nula para cada estadistica y concluimos que los Pokémon legendarios tienen estadísticas medias significativamente diferentes en comparación con los Pokémon no legendarios.

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [12]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:
- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
- Divide your dataset into houses close and far from either a hospital or school.
- Choose the propper test and, with 5% significance, comment your findings.

#### Coordenadas de School y Hospital 
- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

Le pongo nombre a las casas

In [13]:
df["numero_casa"] = "casa" + (df.index + 1).astype(str)
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,numero_casa
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,casa1
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,casa2
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,casa3
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,casa4
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,casa5
...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0,casa16996
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0,casa16997
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,casa16998
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,casa16999
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0,casa17000

Paso las casas al inicio por que me gusta verlas en la primera columna

In [14]:
df.insert(0, 'numero_casa', df.pop('numero_casa'))
df.head()

,numero_casa,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,casa1,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,casa2,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,casa3,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,casa4,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,casa5,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

Vamos a ver la distancia

Funcion euclidea : para 2 puntos P1(x1,y1) p2(x2,y2) la distancia euclidea es:  
np.sqrt((x1 - x2)**2 + (y1 - y2)**2)

In [15]:
import numpy as np

def dist(x1, y1, x2, y2):
    return np.sqrt((x1 - x2)**2 + (y1 - y2)**2)

In [16]:
School_coordinates= (-118, 34)
Hospital_coordinates = (-122, 37)

x1_school, x2_school = School_coordinates
x1_hospital, x2_hospital = Hospital_coordinates

In [17]:
def dist(x1, y1, x2, y2):
    return np.sqrt((x1 - x2)**2 + (y1 - y2)**2)

In [18]:
df['distancia_hospital'] = dist(x1_hospital,x2_hospital,df['longitude'],df['latitude'])
df['distancia_school'] = dist(x1_school,x2_school,df['longitude'],df['latitude'])
df

,numero_casa,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,distancia_hospital,distancia_school
0,casa1,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,8.187319,3.694888
1,casa2,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,7.966235,3.552591
2,casa3,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,8.143077,3.453940
3,casa4,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,8.154416,3.448840
4,casa5,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,8.183508,3.456848
...,...,...,...,...,...,...,...,...,...,...,...,...
16995,casa16996,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0,4.233675,9.082070
16996,casa16997,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0,4.332320,9.168915
16997,casa16998,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,5.358694,10.057614
16998,casa16999,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,5.322593,10.026465
16999,casa17000,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0,4.249012,9.115597

A mi me gusta hacerlo con lambda que puedes poner lo que quieras en vez de la x con una condicion

In [19]:
df["cercany_hospital"] = df["distancia_hospital"].apply(lambda x: True if x < 0.5 else False) # valor celda es 'lower' si x<0.5 sino 'far'
df["cercany_school"] = df["distancia_school"].apply(lambda x: True if x < 0.5 else False)
df['close_hospital_or_scholl'] = df["cercany_hospital"] | df["cercany_school"]

In [20]:
df

,numero_casa,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,distancia_hospital,distancia_school,cercany_hospital,cercany_school,close_hospital_or_scholl
0,casa1,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,8.187319,3.694888,False,False,False
1,casa2,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,7.966235,3.552591,False,False,False
2,casa3,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,8.143077,3.453940,False,False,False
3,casa4,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,8.154416,3.448840,False,False,False
4,casa5,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,8.183508,3.456848,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16995,casa16996,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0,4.233675,9.082070,False,False,False
16996,casa16997,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0,4.332320,9.168915,False,False,False
16997,casa16998,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,5.358694,10.057614,False,False,False
16998,casa16999,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,5.322593,10.026465,False,False,False
16999,casa17000,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0,4.249012,9.115597,False,False,False

In [21]:
df['cercany_hospital'].value_counts()

cercany_hospital
False    15839
True      1161
Name: count, dtype: int64

In [22]:
df['cercany_school'].value_counts()

cercany_school
False    11332
True      5668
Name: count, dtype: int64

In [23]:
df.columns

Index(['numero_casa', 'longitude', 'latitude', 'housing_median_age',
       'total_rooms', 'total_bedrooms', 'population', 'households',
       'median_income', 'median_house_value', 'distancia_hospital',
       'distancia_school', 'cercany_hospital', 'cercany_school',
       'close_hospital_or_scholl'],
      dtype='str')

In [24]:
df_estudio =df[['numero_casa', 'cercany_hospital', 'cercany_school','close_hospital_or_scholl','median_house_value']]
df_estudio

,numero_casa,cercany_hospital,cercany_school,close_hospital_or_scholl,median_house_value
0,casa1,False,False,False,66900.0
1,casa2,False,False,False,80100.0
2,casa3,False,False,False,85700.0
3,casa4,False,False,False,73400.0
4,casa5,False,False,False,65500.0
...,...,...,...,...,...
16995,casa16996,False,False,False,111400.0
16996,casa16997,False,False,False,79000.0
16997,casa16998,False,False,False,103600.0
16998,casa16999,False,False,False,85800.0
16999,casa17000,False,False,False,94600.0

In [25]:
df_estudio['close_hospital_or_scholl'].value_counts()  # asi se los que me van a dar

close_hospital_or_scholl
False    10171
True      6829
Name: count, dtype: int64

In [26]:
close_hospital_or_scholl = df_estudio[df_estudio['close_hospital_or_scholl'] == True]['median_house_value']  # grupos cerca de alguno
far_hospital_or_scholl  = df_estudio[df_estudio['close_hospital_or_scholl'] == False]['median_house_value']   # grupos no cerca de ninguno

In [27]:
# H0 =	Las casas cercanas y lejanas tienen el mismo precio medio  # Si p_value > alpha -> Aceptamos hipótesis nula
# H1 =  Las casas cercanas son más (>) caras que las lejanas ( la que ) # Si p_value < alpha -> Rechazamos hipótesis nula -> Aceptamos la hipótesis alternativa

from scipy.stats import ttest_ind

t_stat, p_value = ttest_ind(close_hospital_or_scholl, far_hospital_or_scholl, equal_var=False) # evalua los dos grupos COMPARANDO CERCA O LEJOS EN RELACION AL PRECIO
print("t =", t_stat, "p =", p_value)

t = 37.992330214201516 p = 3.0064957768591797e-301

In [29]:
alpha = 0.05

if p_value < alpha:
    print("RECHAZA hipotesis nula → Las casas mas cercanas son mas caras")
else:
    print("NO RECHAZA hipotesis nula pero No asegura que las casas sean mas caras por cercania")

RECHAZA hipotesis nula → Las casas mas cercanas son mas caras